name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Add permissions for consistency
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, amd64, armv7]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: matrix.arch == 'armv7'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./chisel
          platforms: linux/${{ matrix.arch == 'armv7' && 'arm/v7' || matrix.arch }}
          push: false
          load: true
          tags: chisel:test-${{ matrix.arch }}
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/base/${{ matrix.arch }}:18.0.2
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            BUILD_DESCRIPTION="Chisel Home Assistant Add-on"
            BUILD_NAME="Chisel"
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_VERSION=dev 