name: Build ARMv7 (Debug)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-armv7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (ARMv7)
        uses: docker/build-push-action@v5
        with:
          context: ./chisel
          platforms: linux/arm/v7
          push: false
          load: true
          tags: chisel:test-armv7-debug
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/base/armv7:18.0.2
            BUILD_ARCH=armv7
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            BUILD_DESCRIPTION="Chisel Home Assistant Add-on"
            BUILD_NAME="Chisel"
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_VERSION=dev 