name: Release

on:
  push:
    tags:
      - 'v*'

# Add permissions for GitHub Container Registry
permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, amd64, armv7]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: matrix.arch == 'armv7'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./chisel
          platforms: linux/${{ matrix.arch == 'armv7' && 'arm/v7' || matrix.arch }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.arch }}:${{ steps.version.outputs.VERSION }}
            ghcr.io/${{ github.repository }}/${{ matrix.arch }}:latest
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/base/${{ matrix.arch }}:18.0.2
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            BUILD_DESCRIPTION="Chisel Home Assistant Add-on"
            BUILD_NAME="Chisel"
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_VERSION=${{ steps.version.outputs.VERSION }}

  create-release:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            ## Chisel Home Assistant Add-on v${{ steps.version.outputs.VERSION }}
            
            ### What's New
            - Initial release of the Chisel addon for Home Assistant
            - Support for multiple architectures (aarch64, amd64, armv7)
            - Server and client modes
            - Secure tunneling and port forwarding capabilities
            
            ### Installation
            1. Add this repository to your Home Assistant instance
            2. Install the Chisel addon
            3. Configure as either server or client
            4. Start the addon
            
            ### Documentation
            See the [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for detailed configuration options.
            
            ### Docker Images
            - `ghcr.io/${{ github.repository }}/aarch64:${{ steps.version.outputs.VERSION }}`
            - `ghcr.io/${{ github.repository }}/amd64:${{ steps.version.outputs.VERSION }}`
            - `ghcr.io/${{ github.repository }}/armv7:${{ steps.version.outputs.VERSION }}`
          draft: false
          prerelease: false 